name = "cloudflare-worker-pixel-router"
main = "src/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./src/admin/ui"
# KV Namespace for pixel configuration
[[kv_namespaces]]
binding = "PIXEL_CONFIG"
id = "de87977f940b497b85e952b8fee620b3" # Updated PIXEL_CONFIG ID

# KV Namespace for pixel state
[[kv_namespaces]]
binding = "PIXEL_STATE"
id = "0d279ec802c34455863cbd272e55d5d7"

# Development environment
[env.dev]
[env.dev.vars]
ENVIRONMENT = "dev"
ENCRYPTION_SECRET = "123" # !!! REPLACE THIS WITH A REAL SECRET !!!

[[env.dev.kv_namespaces]]
binding = "PIXEL_CONFIG"
preview_id = "" # Explicitly enable local simulation

[[env.dev.kv_namespaces]]
binding = "PIXEL_STATE"
# id = "..." # Omit ID for local simulation

# Production environment
[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.kv_namespaces]]
binding = "PIXEL_CONFIG"
id = "de87977f940b497b85e952b8fee620b3" # Updated PIXEL_CONFIG ID

[[env.production.kv_namespaces]]
binding = "PIXEL_STATE"
id = "0d279ec802c34455863cbd272e55d5d7"

[vars]
# Default values for testing (overridden in production)
STICKYIO_API_KEY = "test_key"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true




