name = "cloudflare-worker-pixel-router"
main = "src/handler.ts"
compatibility_date = "2024-04-01"
type = "module"

[build]
command = "npm run build"

[[kv_namespaces]]
binding = "PIXEL_CONFIG"
id = "d6db5d0cfcb14e98b2d7f1bd5567f74f"
preview_id = ""