import { Env } from './types'; // Keep Env type import if needed globally or by router
import { ExecutionContext } from '@cloudflare/workers-types';
import { routeRequest } from './router'; // Import the main router

export default {
  /**
   * Main fetch handler for the Cloudflare Worker.
   * Delegates all requests to the central router.
   * @param request - The incoming request.
   * @param env - The environment bindings (KV namespaces, secrets).
   * @param ctx - The execution context.
   * @returns The response generated by the appropriate handler.
   */
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    // Delegate all routing logic to the routeRequest function
    return routeRequest(request, env, ctx);
  },
};

// All previous handler logic, helper functions, type definitions, etc.,
// should now be removed from this file as they have been moved to their
// respective modules (handlers/*, lib/*, middleware/*, utils/*, types.ts, router.ts).