import type { KVNamespace } from '@cloudflare/workers-types';

// Environment variables expected by the Worker
export interface Env {
	// KV Namespaces
	PIXEL_STATE: KVNamespace; // Stores state for individual pixel fires (e.g., transaction details)
	PIXEL_CONFIG: KVNamespace; // Stores site configuration, action definitions, etc.
	ADMIN_UI_ASSETS: KVNamespace; // For serving the admin UI static files

	// Secrets / API Keys
	ADMIN_USERNAME?: string; // Basic Auth username for admin UI
	ADMIN_PASSWORD?: string; // Basic Auth password hash for admin UI
	JWT_SECRET: string; // Secret for signing JWTs for admin sessions

	FB_PIXEL_ID?: string; // Default Facebook Pixel ID
	FB_ACCESS_TOKEN?: string; // Facebook Conversions API Access Token
	FB_TEST_CODE?: string; // Optional Facebook Test Event Code

	GA_MEASUREMENT_ID?: string; // Optional Google Analytics Measurement ID (e.g., G-XXXX)
	GA_API_SECRET?: string; // Optional Google Analytics Measurement Protocol API Secret

	EF_COMPANY_ID?: string; // Optional Everflow Company ID
	EF_API_KEY?: string; // Optional Everflow API Key

	STICKY_API_URL?: string; // Sticky.io API endpoint URL
	STICKY_USERNAME?: string; // Sticky.io API username
	STICKY_PASSWORD?: string; // Sticky.io API password

	// Add other environment variables as needed
	// MY_OTHER_VARIABLE: string;
}

// Structure for storing the state of a pixel transaction in KV
export interface PixelState {
	internal_txn_id: string; // Unique ID generated by the worker
	siteId: string; // The site ID this transaction belongs to
	timestamp_created: string; // ISO 8601 timestamp when the state was first created
	status?: 'pending' | 'processed' | 'error'; // Status of the pixel processing (optional initially)
	trackingParams: { // Parameters captured from the initial request
		[key: string]: string | undefined; // Allow flexible tracking params like click_id, affId, c1, c2, c3 etc.
	};
	scrubDecision?: { // Decision from the scrubbing process (optional)
		isScrub: boolean;
		reason?: string;
		targetCampaignId?: string; // e.g., the campaign ID to route to after scrubbing
	};
		 stickyOrderId_Initial?: string | null; // Sticky.io Order ID from the initial purchase
		 targetCampaignId?: string | null; // Campaign ID determined during checkout/scrubbing, used for upsells
	// Flags to track processing stages (can add more for different event types)
	processed_Initial: boolean;
	processed_Upsell_1: boolean;
	processed_Upsell_2: boolean; // Example for a second upsell step
	// Timestamps for processing stages
	timestamp_processed_Initial: string | null;
	timestamp_processed_Upsell_1: string | null;
	// Add more fields as needed, e.g., specific data points required for later actions
	// customer_email?: string; // Example: Store email if needed for delayed actions
}

// --- Configuration Types (Stored in PIXEL_CONFIG KV) ---

// Defines configuration specific to a site/domain
export interface SiteConfig {
	siteId: string; // e.g., 'drivebright'
	domain: string; // e.g., 'www.drivebright.com'
	pages: Record<string, PageConfig>; // Map page identifiers (e.g., 'checkout', 'upsell1') to their configs
	payoutConfig?: PayoutConfig; // Optional payout configuration
	// Add other site-level settings like default pixel IDs if needed
}

// Defines configuration for a specific page within a site
export interface PageConfig {
	pageId: string; // Matches the key in SiteConfig.pages (e.g., 'checkout')
	pathPattern: string; // Regex pattern to match the page URL path (e.g., '/checkout.*')
	event: 'Initial' | 'Upsell_1' | 'Upsell_2'; // Type of event this page corresponds to
	actions: {
		normal: string[]; // List of action keys (e.g., ['fb_purchase', 'ga_purchase', 'ef_postback']) for normal processing
		scrub?: string[]; // Optional list of action keys for scrubbed transactions
	};
}

// Defines payout settings, potentially per affiliate
export interface PayoutConfig {
	defaultPayoutSteps: number; // Default number of steps required for payout (e.g., 1 for initial, 2 for initial+upsell1)
	affiliatePayoutSteps?: Record<string, number>; // Override payout steps per affiliate ID (e.g., { 'aff123': 2 })
}

// Defines a single action (pixel fire, server postback, etc.)
// Using discriminated union for type safety based on 'type'
export type ActionDefinition = ServerSideActionDefinition | ClientSideActionDefinition;

interface ActionDefinitionBase {
	actionKey: string; // Unique key for this action (e.g., 'fb_purchase_capi')
	provider: string; // e.g., 'facebook', 'google', 'everflow', 'custom'
	type: 'server-side' | 'client-side';
}

export interface ServerSideActionDefinition extends ActionDefinitionBase {
	type: 'server-side';
	config: ApiEndpointConfig; // Configuration for the API call
}

export interface ClientSideActionDefinition extends ActionDefinitionBase {
	type: 'client-side';
	config: PixelConfig; // Configuration for the client-side script/pixel
}


// Configuration for a server-side API endpoint action
export interface ApiEndpointConfig {
	url: string; // URL template for the API endpoint (can include PARAM:* placeholders)
	method: 'GET' | 'POST' | 'PUT' | 'DELETE';
	headers?: Record<string, string>; // Header templates (can include PARAM:* placeholders)
	body_template?: Record<string, any> | string; // JSON object or string template for the request body (can include PARAM:*)
	// Add authentication details if needed (e.g., apiKeyParam: 'PARAM:SOME_API_KEY')
}

// Configuration for a client-side pixel/script action
export interface PixelConfig {
	script_template: string; // HTML/JS script template (can include PARAM:* placeholders)
	// Add other relevant config like placement ('head', 'body') if needed
}


// --- Admin API Types ---
export interface KvListResponse {
    keys: { name: string; expiration?: number; metadata?: unknown }[];
    list_complete: boolean;
    cursor?: string;
}

export interface KvWriteRequest {
    key: string;
    value: string;
    expirationTtl?: number; // Optional TTL in seconds
    metadata?: any; // Optional metadata
}

export interface KvReadResponse {
    value: string | null;
    metadata?: any;
}

export interface KvDeleteRequest {
    keys: string[];
}